### ISSUE TITLE
Cannot read property 'split' of null

### ISSUE THREAD

**Issue by vichanse** [momenttech/lysis#3]
Hi David,

I'm having this error when i run lysis on one of my projects.
![image](https://user-images.githubusercontent.com/26761479/32881551-e5fcdd7a-cab1-11e7-8a46-306c88244050.png)

Is there any way that i can have access to lysis logs?
Have you any idea of where it can come from?

Thank you for your answer

**Comment by partageit** [comment]
Hi Vicky,

I have an idea :)

A property in you API Platform is not linked to the ORM and doesn't have `@type` annotation.

```php
class Book {
  // [...]
  /**
   * this one is typed via ORM
   * @ORM\Column(type="string", length=255, nullable=true)
   */
  protected $field1;

  /**
   * this one is typed via docblock annotation
   * @var string
   */
  protected $field2;

  /**
   * this one is not typed and leads to a 'Cannot read property 'split' of null
   */
  protected $field3;
  // [...]
}
```

In the next lysis version, I will catch this error, with a proper error message.

**Comment by vichanse** [comment]
Hi David,

Gr8. Problem solved 👍
